# Generated by Django 5.2.8 on 2025-11-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consumidor", "0002_reserva"),
    ]

    operations = []
