# Generated by Django 5.2.8 on 2025-11-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumidor", "0003_auto_20251120_1340"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="email_cliente",
            field=models.EmailField(default="cliente@exemplo.com", max_length=254),
            preserve_default=False,
        ),
    ]
