# Generated by Django 5.2.8 on 2025-11-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumidor", "0004_reserva_email_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
    ]
