# Generated by Django 5.2.8 on 2025-11-28 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumidor', '0004_reserva_email_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='estoque',
        ),
        migrations.AddField(
            model_name='item',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade_estoque',
            field=models.IntegerField(db_column='quantidade_estoque', default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(max_length=254)),
                ('notificado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='consumidor.item')),
            ],
            options={
                'unique_together': {('email_cliente', 'item')},
            },
        ),
    ]
