# Generated by Django 5.2.8 on 2025-11-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumidor", "0006_emailsubscription_reserva_confirmado_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="estoque",
            new_name="quantidade_estoque",
        ),
        migrations.AddField(
            model_name="item",
            name="disponivel",
            field=models.BooleanField(default=True),
        ),
    ]
