# Generated by Django 5.2.8 on 2025-11-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consumidor", "0007_rename_estoque_item_quantidade_estoque_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notificacao",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="notificacao",
            name="quantidade",
            field=models.IntegerField(default=1),
        ),
    ]
